# Usa una imagen base de Python
FROM python:3.10.16-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo de requerimientos y los instala
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código al contenedor
COPY . .

# Define el entrypoint para el script de entrenamiento
ENTRYPOINT ["python", "train.py"]